#Mi primer workflow
#nombre
name: "Hola mundo"

#Trigger
on:
    push:
        branches: ["main"]

#Tareas
jobs:
    #nombre de la tarea
    deploy-codigofacilito:
        #maquina virtual
        runs-on: ubuntu-latest
        #Pasos
        steps:
            - uses: actions/checkout@v4                 #Comando para descargar el repo
            - run: echo "Hacemos pull del codigo"       #Imprimir mensaje
            - run: echo "Correr migraciones"            #Imprimir mensaje
            - run: echo "Generar binario"               #Imprimir mensaje
            - run: echo "Publicar version"              #Imprimir mensaje
            #nombre de la tarea
    send-notification:
        #maquina virtual
        runs-on: ubuntu-latest
        #Pasos
        steps:
            - run: echo "Tarea donde se mandan las notificaciones"
    #nombre de la tarea
    test-code:
        #maquina virtual
        runs-on: ubuntu-latest
        #Pasos
        steps:
            - run: echo "Tarea donde se testea el codigo"