#Mi primer workflow
#nombre
name: "Hola mundo"

#Trigger
on:
    push:
        branches:
            - "main"
            - "develop"

#Tareas
jobs:
    #nombre de la tarea
    ImprimirMensajesEnLaRamaMain:
        #Codicional
        if: github.ref == 'refs/heads/main'
        #maquina virtual
        runs-on: ubuntu-latest
        #Pasos
        steps:
            - uses: actions/checkout@v4                 #Comando para descargar el repo
            - run: echo "Funciono estas en la rama main"       #Imprimir mensaje
            
    #nombre de la tarea
    ImprimirMensajesEnLaRamaDevelop:
        #Codicional
        if: github.ref == 'refs/heads/develop'
        #maquina virtual
        runs-on: ubuntu-latest
        #Pasos
        steps:
            - uses: actions/checkout@v4                 #Comando para descargar el repo
            - run: echo "Funciono estas en la segunda rama develop"       #Imprimir mensaje
            