name: Deploy to server

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        env:
            VARIBALES_DE_ENTORNO: CodigoFacilito

        steps:
            - name: Working dir
              id: step_1
              run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

            - name: Obtener mensaje
              run: echo "${{steps.step_1.outputs.my_variable}}"

    second_job:
        #${{}} contexto
        # Condicionar el job, verificar si el flujo de trabajo se está ejecutando en la rama principal
        #Es decir que se ejecute si el flujo de trabajo fue activado en la rama principal
        if: ${{github.ref == 'refs/heads/main'}}
        needs: first_job
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo 2
            #Saber el valor de este paso
              run: echo "Hola mundo ${{github.ref}}"