name: Deploy to server

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        env:
            VARIBALES_DE_ENTORNO: CodigoFacilito

        outputs:
         salida: ${{steps.step_1.outputs.my_variable}}

        steps:
            - name: Generar archivo
              run: |
               echo "Archivo prueba, hola" >> test.log

            - name: Subir artefacto
              uses: actions/upload-artifact@v4
              with:
                name: archivo-test
                path: test.log #carpeta o archivo

    segundo_trabajo:
        runs-on: ubuntu-latest
        #Se agrega debido a que los jobs se ejecutan en paralelo, y puede que el segundo trabajo termine primero
        needs: first_job

        steps:
            - name: Descargar Artefacto
              uses: actions/download-artifact@4
              with:
                name: archivo-test