name: Deploy to server

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        env:
            VARIBALES_DE_ENTORNO: CodigoFacilito

        steps:
            - name: Hola Mundo
              run: echo "Hola mundo $VARIABLES_DE_ENTORNO"

            #Ver en que directorio estamos
            - name: Working dir
              run: ls -al

    second_job:
        #${{}} contexto
        # Condicionar el job, verificar si el flujo de trabajo se está ejecutando en la rama principal
        #Es decir que se ejecute si el flujo de trabajo fue activado en la rama principal
        if: ${{github.ref == 'refs/heads/main'}}
        needs: first_job
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo 2
            #Saber el valor de este paso
              run: echo "Hola mundo ${{github.ref}}"